POST http://localhost:3000/profile/createNewProfile 
Content-Type: application/json

{
    "name":"raj",
    "dob":"2001-7-28",
    "status":"Paused"
}

PUT http://localhost:3000/profile/pauseUnpauseprofile 
Content-Type: application/json

{
    "id":2,
    "choice":"unpause"
}
